title: My variables do not appear in the Inspector
hero_image: images/banner.png
description: My variables do not appear in the Inspector
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - 
    title: My variables do not appear in the Inspector
